require('dotenv').config();
const express=require('express'),session=require('express-session'),Database=require('better-sqlite3'),crypto=require('crypto'),path=require('path'),helmet=require('helmet');
const app=express(),PORT=Number(process.env.PORT||3000),prod=process.env.NODE_ENV==='production';
if(prod)app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'256kb'}));
app.use(session({name:'songli.sid',secret:process.env.SESSION_SECRET||'dev-secret-change-me',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:prod,maxAge:7*86400000}}));
const db=new Database(path.join(__dirname,'songli.db'));db.pragma('journal_mode=WAL');db.pragma('foreign_keys=ON');
db.exec(`CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE NOT NULL,title TEXT NOT NULL,welcome TEXT DEFAULT '',description TEXT DEFAULT '',access_mode TEXT DEFAULT 'private',guest_password_hash TEXT,songs_per_guest INTEGER DEFAULT 3,reveal_mode TEXT DEFAULT 'normal',playlist_order TEXT DEFAULT 'chronological',creator_password_hash TEXT NOT NULL,status TEXT DEFAULT 'active',archived INTEGER DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS guests(id INTEGER PRIMARY KEY AUTOINCREMENT,event_id INTEGER NOT NULL,name TEXT NOT NULL,token_hash TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE);CREATE TABLE IF NOT EXISTS songs(id INTEGER PRIMARY KEY AUTOINCREMENT,event_id INTEGER NOT NULL,guest_id INTEGER NOT NULL,spotify_track_id TEXT NOT NULL,title TEXT NOT NULL,artist TEXT DEFAULT '',album TEXT DEFAULT '',thumbnail TEXT DEFAULT '',spotify_url TEXT DEFAULT '',created_at TEXT NOT NULL,FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE,FOREIGN KEY(guest_id) REFERENCES guests(id) ON DELETE CASCADE,UNIQUE(event_id,spotify_track_id));`);
const now=()=>new Date().toISOString(),sha=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
function hash(p){const s=crypto.randomBytes(16),h=crypto.scryptSync(p,s,64);return s.toString('hex')+':'+h.toString('hex')}
function verify(p,x){try{const [s,h]=String(x||'').split(':'),d=crypto.scryptSync(p,Buffer.from(s,'hex'),64),e=Buffer.from(h,'hex');return d.length===e.length&&crypto.timingSafeEqual(d,e)}catch{return false}}
const txt=(v,n=5000)=>String(v??'').trim().slice(0,n),codeOk=c=>/^\d{4}$/.test(String(c)),limitOk=n=>Number.isInteger(Number(n))&&Number(n)>=1&&Number(n)<=10;
function code4(){for(;;){const c=String(crypto.randomInt(0,10000)).padStart(4,'0');if(!db.prepare('SELECT 1 FROM events WHERE code=?').get(c))return c}}
function token(){return crypto.randomBytes(32).toString('base64url')}
function ev(c){return db.prepare('SELECT * FROM events WHERE code=?').get(c)}
function eid(id){return db.prepare('SELECT * FROM events WHERE id=?').get(id)}
function pub(e){return {id:e.id,code:e.code,title:e.title,welcome:e.welcome,description:e.description,accessMode:e.access_mode,requiresGuestPassword:!!e.guest_password_hash,songsPerGuest:e.songs_per_guest,revealMode:e.reveal_mode,playlistOrder:e.playlist_order,status:e.status,archived:!!e.archived,createdAt:e.created_at,updatedAt:e.updated_at}}
function full(e){return {...pub(e),hasCreatorPassword:!!e.creator_password_hash}}
function guest(req,eventId){const id=Number(req.body?.guestId??req.query?.guestId),t=String(req.body?.token??req.query?.token??'');if(!id||!t)return null;const g=db.prepare('SELECT * FROM guests WHERE id=? AND event_id=?').get(id,eventId);return g&&sha(t)===g.token_hash?g:null}
function songs(eventId){return db.prepare('SELECT s.*,g.name guest_name FROM songs s JOIN guests g ON g.id=s.guest_id WHERE s.event_id=? ORDER BY s.id').all(eventId).map(s=>({id:s.id,spotifyTrackId:s.spotify_track_id,title:s.title,artist:s.artist,album:s.album,thumbnail:s.thumbnail,spotifyUrl:s.spotify_url,guestId:s.guest_id,guestName:s.guest_name,createdAt:s.created_at}))}
function creator(req,res,next){if(req.session.creatorEventId)return next();res.status(401).json({ok:false,error:'Creator-Anmeldung erforderlich.'})}
function admin(req,res,next){if(req.session.admin)return next();res.status(401).json({ok:false,error:'Admin-Anmeldung erforderlich.'})}
app.get('/api/health',(q,r)=>r.json({ok:true,data:{database:!!db.prepare('SELECT 1').get(),uptime:process.uptime(),node:process.version}}));
app.get('/api/status',(q,r)=>r.json({ok:true,data:{spotifyConfigured:!!(process.env.SPOTIFY_CLIENT_ID&&process.env.SPOTIFY_CLIENT_SECRET),creatorLoggedIn:!!q.session.creatorEventId,adminLoggedIn:!!q.session.admin}}));
app.post('/api/events',(req,res)=>{const b=req.body||{},title=txt(b.title,120),access=b.accessMode||'private',n=Number(b.songsPerGuest),reveal=b.revealMode||'normal',order=b.playlistOrder||'chronological',cp=String(b.creatorPassword||''),gp=String(b.guestPassword||'');if(!title)return res.status(400).json({ok:false,error:'Bitte einen Eventnamen eingeben.'});if(!['private','public'].includes(access))return res.status(400).json({ok:false,error:'Ungültiger Zugangsmodus.'});if(!limitOk(n))return res.status(400).json({ok:false,error:'Songs pro Gast muss zwischen 1 und 10 liegen.'});if(!['normal','after_limit','secret'].includes(reveal))return res.status(400).json({ok:false,error:'Ungültiger Sichtbarkeitsmodus.'});if(!['chronological','random'].includes(order))return res.status(400).json({ok:false,error:'Ungültige Playlist-Reihenfolge.'});if(cp.length<6)return res.status(400).json({ok:false,error:'Das Creator-Passwort muss mindestens 6 Zeichen haben.'});const t=now(),c=code4(),x=db.prepare('INSERT INTO events(code,title,welcome,description,access_mode,guest_password_hash,songs_per_guest,reveal_mode,playlist_order,creator_password_hash,status,archived,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(c,title,txt(b.welcome,1000),txt(b.description),access,gp?hash(gp):null,n,reveal,order,hash(cp),'active',0,t,t);res.status(201).json({ok:true,data:full(eid(x.lastInsertRowid))})});
app.get('/api/events/:code',(req,res)=>{if(!codeOk(req.params.code))return res.status(400).json({ok:false,error:'Ungültiger 4-stelliger Event-Code.'});const e=ev(req.params.code);if(!e)return res.status(404).json({ok:false,error:'Event nicht gefunden.'});res.json({ok:true,data:pub(e)})});
app.post('/api/events/:code/join',(req,res)=>{const e=ev(req.params.code);if(!e)return res.status(404).json({ok:false,error:'Event nicht gefunden.'});if(e.archived||e.status!=='active')return res.status(403).json({ok:false,error:'Dieses Event ist nicht aktiv.'});const name=txt(req.body.name,80),pw=String(req.body.password||'');if(!name)return res.status(400).json({ok:false,error:'Bitte deinen Namen eingeben.'});if(e.guest_password_hash&&!verify(pw,e.guest_password_hash))return res.status(401).json({ok:false,error:'Gäste-Passwort ist falsch.'});const t=token(),x=db.prepare('INSERT INTO guests(event_id,name,token_hash,created_at) VALUES(?,?,?,?)').run(e.id,name,sha(t),now());res.status(201).json({ok:true,data:{guestId:x.lastInsertRowid,token:t,name,event:pub(e)}})});
app.get('/api/events/:code/me',(req,res)=>{const e=ev(req.params.code);if(!e)return res.status(404).json({ok:false,error:'Event nicht gefunden.'});const g=guest(req,e.id);if(!g)return res.status(401).json({ok:false,error:'Gast-Anmeldung ungültig.'});const count=db.prepare('SELECT COUNT(*) c FROM songs WHERE event_id=? AND guest_id=?').get(e.id,g.id).c;let list=[];if(e.reveal_mode!=='secret'&&(e.reveal_mode!=='after_limit'||count>=e.songs_per_guest))list=songs(e.id);res.json({ok:true,data:{guest:{guestId:g.id,name:g.name},event:pub(e),songsUsed:count,songsRemaining:Math.max(0,e.songs_per_guest-count),songs:list}})});
app.post('/api/events/:code/songs',(req,res)=>{const e=ev(req.params.code);if(!e)return res.status(404).json({ok:false,error:'Event nicht gefunden.'});const g=guest(req,e.id);if(!g)return res.status(401).json({ok:false,error:'Gast-Anmeldung ungültig.'});const count=db.prepare('SELECT COUNT(*) c FROM songs WHERE event_id=? AND guest_id=?').get(e.id,g.id).c;if(count>=e.songs_per_guest)return res.status(409).json({ok:false,error:'Dein Song-Limit ist erreicht.'});const id=txt(req.body.spotifyTrackId||req.body.trackId,100),title=txt(req.body.title,300);if(!id||!title)return res.status(400).json({ok:false,error:'Songdaten fehlen.'});try{const x=db.prepare('INSERT INTO songs(event_id,guest_id,spotify_track_id,title,artist,album,thumbnail,spotify_url,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(e.id,g.id,id,title,txt(req.body.artist,300),txt(req.body.album,300),txt(req.body.thumbnail,1000),txt(req.body.spotifyUrl,1000),now());res.status(201).json({ok:true,data:{id:x.lastInsertRowid}})}catch(err){if(String(err.message).includes('UNIQUE'))return res.status(409).json({ok:false,error:'Dieser Song wurde bereits zum Event hinzugefügt.'});throw err}});
app.delete('/api/events/:code/songs/:songId',(req,res)=>{const e=ev(req.params.code),g=e&&guest(req,e.id);if(!e)return res.status(404).json({ok:false,error:'Event nicht gefunden.'});if(!g)return res.status(401).json({ok:false,error:'Gast-Anmeldung ungültig.'});const x=db.prepare('DELETE FROM songs WHERE id=? AND event_id=? AND guest_id=?').run(Number(req.params.songId),e.id,g.id);if(!x.changes)return res.status(404).json({ok:false,error:'Eigener Song nicht gefunden.'});res.json({ok:true,data:{deleted:true}})});
async function spToken(){const a=process.env.SPOTIFY_CLIENT_ID,b=process.env.SPOTIFY_CLIENT_SECRET;if(!a||!b)throw Error('Spotify ist auf dem Server nicht konfiguriert.');const z=Buffer.from(`${a}:${b}`).toString('base64'),r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{Authorization:`Basic ${z}`,'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});if(!r.ok)throw Error('Spotify-Authentifizierung fehlgeschlagen.');return (await r.json()).access_token}
app.get('/api/spotify/search',async(req,res)=>{try{const q=txt(req.query.q,200);if(q.length<2)return res.json({ok:true,data:[]});const t=await spToken(),r=await fetch(`https://api.spotify.com/v1/search?type=track&limit=10&q=${encodeURIComponent(q)}`,{headers:{Authorization:`Bearer ${t}`}});if(!r.ok)throw Error('Spotify-Suche fehlgeschlagen.');const d=await r.json(),items=(d.tracks?.items||[]).map(x=>({spotifyTrackId:x.id,title:x.name,artist:x.artists?.map(a=>a.name).join(', ')||'',album:x.album?.name||'',thumbnail:x.album?.images?.[0]?.url||'',spotifyUrl:x.external_urls?.spotify||''}));res.json({ok:true,data:items})}catch(e){res.status(503).json({ok:false,error:e.message})}});
app.post('/api/creator/login',(req,res)=>{const c=String(req.body.code||''),p=String(req.body.password||'');const e=codeOk(c)&&ev(c);if(!e||!verify(p,e.creator_password_hash))return res.status(401).json({ok:false,error:'Event oder Passwort ist falsch.'});req.session.creatorEventId=e.id;res.json({ok:true,data:full(e)})});
app.post('/api/creator/logout',(req,res)=>{delete req.session.creatorEventId;res.json({ok:true,data:{loggedOut:true}})});
app.get('/api/creator/events/:id',creator,(req,res)=>{const e=eid(req.params.id);if(!e||e.id!==req.session.creatorEventId)return res.status(403).json({ok:false,error:'Kein Zugriff auf dieses Event.'});const gs=db.prepare('SELECT id,name,created_at FROM guests WHERE event_id=? ORDER BY id').all(e.id);res.json({ok:true,data:{event:full(e),guests:gs,songs:songs(e.id)}})});
app.patch('/api/creator/events/:id',creator,(req,res)=>{const e=eid(req.params.id);if(!e||e.id!==req.session.creatorEventId)return res.status(403).json({ok:false,error:'Kein Zugriff auf dieses Event.'});const fields=[],vals=[];if(req.body.songsPerGuest!==undefined){if(!limitOk(req.body.songsPerGuest))return res.status(400).json({ok:false,error:'Songs pro Gast muss zwischen 1 und 10 liegen.'});fields.push('songs_per_guest=?');vals.push(Number(req.body.songsPerGuest))}if(req.body.revealMode!==undefined){if(!['normal','after_limit','secret'].includes(req.body.revealMode))return res.status(400).json({ok:false,error:'Ungültiger Sichtbarkeitsmodus.'});fields.push('reveal_mode=?');vals.push(req.body.revealMode)}if(req.body.playlistOrder!==undefined){if(!['chronological','random'].includes(req.body.playlistOrder))return res.status(400).json({ok:false,error:'Ungültige Reihenfolge.'});fields.push('playlist_order=?');vals.push(req.body.playlistOrder)}if(fields){if(fields.length)db.prepare(`UPDATE events SET ${fields.join(',')},updated_at=? WHERE id=?`).run(...vals,now(),e.id)}res.json({ok:true,data:full(eid(e.id))})});
app.delete('/api/creator/events/:id/songs/:songId',creator,(req,res)=>{const e=eid(req.params.id);if(!e||e.id!==req.session.creatorEventId)return res.status(403).json({ok:false,error:'Kein Zugriff.'});db.prepare('DELETE FROM songs WHERE id=? AND event_id=?').run(Number(req.params.songId),e.id);res.json({ok:true,data:{deleted:true}})});
app.get('/api/creator/events/:id/export',creator,(req,res)=>{const e=eid(req.params.id);if(!e||e.id!==req.session.creatorEventId)return res.status(403).send('Kein Zugriff.');const rows=[['Position','Song','Künstler','Album','Gast','Spotify URL','Zeitpunkt'],...songs(e.id).map((s,i)=>[i+1,s.title,s.artist,s.album,s.guestName,s.spotifyUrl,s.createdAt])];const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;res.setHeader('Content-Type','text/csv;charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="songli-${e.code}.csv"`);res.send('\uFEFF'+rows.map(r=>r.map(q).join(';')).join('\r\n'))});
app.delete('/api/creator/events/:id',creator,(req,res)=>{const e=eid(req.params.id);if(!e||e.id!==req.session.creatorEventId)return res.status(403).json({ok:false,error:'Kein Zugriff.'});db.prepare('DELETE FROM events WHERE id=?').run(e.id);delete req.session.creatorEventId;res.json({ok:true,data:{deleted:true}})});
app.post('/api/admin/login',(req,res)=>{if(String(req.body.username||'')!==String(process.env.ADMIN_USERNAME||'')||String(req.body.password||'')!==String(process.env.ADMIN_PASSWORD||''))return res.status(401).json({ok:false,error:'Admin-Zugangsdaten sind falsch.'});req.session.admin=true;res.json({ok:true,data:{loggedIn:true}})});
app.post('/api/admin/logout',admin,(req,res)=>{delete req.session.admin;res.json({ok:true,data:{loggedOut:true}})});
app.get('/api/admin/events',admin,(req,res)=>{const a=db.prepare(`SELECT e.*,(SELECT COUNT(*) FROM guests g WHERE g.event_id=e.id) guest_count,(SELECT COUNT(*) FROM songs s WHERE s.event_id=e.id) song_count FROM events e ORDER BY e.id DESC`).all().map(e=>({...full(e),guestCount:e.guest_count,songCount:e.song_count}));res.json({ok:true,data:a})});
app.get('/api/admin/events/:id',admin,(req,res)=>{const e=eid(req.params.id);if(!e)return res.status(404).json({ok:false,error:'Event nicht gefunden.'});res.json({ok:true,data:{event:full(e),guests:db.prepare('SELECT id,name,created_at FROM guests WHERE event_id=?').all(e.id),songs:songs(e.id)}})});
app.post('/api/admin/events/:id/archive',admin,(req,res)=>{const e=eid(req.params.id);if(!e)return res.status(404).json({ok:false,error:'Event nicht gefunden.'});db.prepare("UPDATE events SET archived=1,status='closed',updated_at=? WHERE id=?").run(now(),e.id);res.json({ok:true,data:full(eid(e.id))})});
app.delete('/api/admin/events/:id',admin,(req,res)=>{const e=eid(req.params.id);if(!e)return res.status(404).json({ok:false,error:'Event nicht gefunden.'});db.prepare('DELETE FROM events WHERE id=?').run(e.id);res.json({ok:true,data:{deleted:true}})});
app.post('/api/admin/events/:id/set-creator-password',admin,(req,res)=>{const e=eid(req.params.id),p=String(req.body.password||'');if(!e)return res.status(404).json({ok:false,error:'Event nicht gefunden.'});if(p.length<6)return res.status(400).json({ok:false,error:'Creator-Passwort muss mindestens 6 Zeichen haben.'});db.prepare('UPDATE events SET creator_password_hash=?,updated_at=? WHERE id=?').run(hash(p),now(),e.id);res.json({ok:true,data:{updated:true}})});
app.use('/api',(req,res)=>res.status(404).json({ok:false,error:'API-Endpunkt nicht gefunden.'}));
app.use(express.static(path.join(__dirname,'public')));
app.get('/{*splat}',(req,res,next)=>req.path.startsWith('/api/')?next():res.sendFile(path.join(__dirname,'public','index.html')));
app.use((err,req,res,next)=>{console.error(err);if(res.headersSent)return next(err);res.status(500).json({ok:false,error:'Interner Serverfehler.'})});
app.listen(PORT,'0.0.0.0',()=>console.log(`Songli läuft auf Port ${PORT}`));
